"""empty message

Revision ID: 4db4fc589abc
Revises: None
Create Date: 2014-03-11 22:23:32.685797

"""

# revision identifiers, used by Alembic.
revision = '4db4fc589abc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'time')
    ### end Alembic commands ###
